apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  labels:
    app: wireguard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: ghcr.io/marizmendi/wireguard:latest
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true
        env:
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: wireguard
              key: private_key
        volumeMounts:
          - name: wireguard
            mountPath: /tmp/wireguard
        command:
        - /bin/sh
        - -c
        - mkdir -p /etc/wireguard/; envsubst < "/tmp/wireguard/wg0.conf.template" > "/etc/wireguard/wg0.conf"; /usr/bin/wg-quick up wg0; sleep infinity
        ports:
        - containerPort: 56565
          protocol: UDP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
        - name: wireguard
          configMap:
            name: wireguard
